### ISSUE TITLE
Kashida problem with most of fonts (except IR series)

### ISSUE THREAD

**Issue by bahman-mirzakhani** [tex-persian/xepersian#12] opened 2022-02-22 19:31 UTC
## Brief outline of the issue
The letters are separated when `Kashida` is enable.
## Check/indicate
- [ ] Relevant to the `bidi` package
- [x] [The `bidi` package issue tracker](https://github.com/tex-persian/bidi/issues) has been searched for similar issues?
- [x] [The `xepersian` package issue tracker](https://github.com/tex-persian/xepersian/issues) has been searched for similar issues?
- [ ] Links to <tex.stackexchange.com> discussion if appropriate
- [ ] Links to <qa.parsilatex.com> discussion if appropriate

## Minimal example showing the issue

```tex
% !TEX TS-program = XeLaTeX
% !TEX encoding = UTF-8 Unicode

\documentclass{article}

\usepackage[Kashida]{xepersian}
 % problem with series: XB, HM FTX 3.8, HM SX2 3.8, Yas and so on...
\settextfont{XB Zar}

\begin{document}
این یک متن آزمایشی است.
\end{document}
```

## Log and PDF files 
[test.log](https://github.com/tex-persian/xepersian/files/8119587/test.log)
[test.pdf](https://github.com/tex-persian/xepersian/files/8119588/test.pdf)

**Comment by vafa-khalighi** [comment] 2022-02-26 11:47
The only fonts I have access to are Adobe Arabic, IRXLotus, Iranian Sans and Apple's shipped Arabic fonts. If you can test using these fonts, it would be wonderful as I do not want to download fonts into my work computer as the fonts you are mentioning may have some legal issues and it could cause me legal headaches at work. Also, these fonts may contain viruses and they could harm my computer.

**Comment by bahman-mirzakhani** [comment] 2022-02-27 19:40
There is no problem with Adobe Arabic, IRXLotus (also IR series) and Iranian Sans fonts.

**Comment by vafa-khalighi** [comment] 2022-02-28 04:22
I am sorry if my message conveyed that you needed to close the issue. Certainly, the issue has existed for several years. I will reopen this issue and see what I can do to fix it.

**Comment by ghost** [comment] 2024-12-17 04:57
I have uploaded version `25.4` of the `xepersian` package to CTAN which should fix this issue.

The cause of the issue was applying left to right mark (`U+200E`) and I removed it to fix the issue. Applying `U+200E` was a nonstandard approach and only was specific to XB Series fonts and various other derived fonts. This worked few years ago but now the behavior of XeTeX / Harfbuzz has changed and this ugly hack no longer works. We should indeed avoid using such nonstandard approaches.

However, this reintroduces an old issue with XB Series font with applying `U+200D` after `U+0647`:
```tex
\font\testfont="[Yas.ttf]:script=arab" at 100pt
\testfont
\char"0647\char"200D\char"0631
\bye
```

<img width="307" alt="Screenshot 2024-12-17 at 3 35 42 PM" src="https://github.com/user-attachments/assets/7f25cc78-0321-42d0-a202-db224016ee49" />


This is a XB Series font issue really and it should be fixed in the font itself. It does not exist in other fonts.

If this addresses your issue, then please consider closing this issue.

**Comment by ghost** [comment] 2024-12-17 06:25
I believe that I found the bug in XB Series fonts and its various other derived fonts with regard to applying `U+200D` after `U+0647`. This issue is also inherited by any other fonts based on XB Series fonts. This is a font bug and should be reported to the effected font authors to be fixed. The exact issue is that

> U0647 + U200D gets replaced by the glyph index 559 while it should be replaced by the glyph index 561

Note that the fix is extremely easy. One has to edit the font opentype tables. Since it is a font bug, I do not consider it a `xepersian` package issue.

```tex
\font\testfont="[Yas.ttf]:script=arab" at 100pt
\testfont
\char"0647\char"200D\char"0631

\XeTeXglyph559 % U0647 + U200D gets replaced by the glyph index 559 while it should be replaced by the glyph index 561

\XeTeXglyph561

\TeXXeTstate=1
\beginR\XeTeXglyph561\char"200D\char"0631\endR


\bye
```
<img width="327" alt="Screenshot 2024-12-17 at 5 12 11 PM" src="https://github.com/user-attachments/assets/928c20c4-fb72-41aa-b30b-9a1e255962bd" />

**Comment by ghost** [comment] 2024-12-17 07:10
Note that the glyph indexes 559 and 561 are specific to XB Yas font. Other fonts probably have different glyph indexes for the same glyph.

**Comment by ghost** [comment] 2024-12-17 07:43
If you actually want the more general version of the font bug in terms of unicode characters rather than the glyph indexes, then here it is:

> U0647 + U200D gets replaced by `U+FBAA` (or `U+06BE`) while it should be replaced by `U+FEEB` (or `U+FBAC`).

**Closed as completed** 2024-12-17 16:27 UTC
Labels: bug
